# Stage 1: Install dependencies only when package.json or lockfile changes
FROM node:20-alpine AS deps
# Add libc6-compat for compatibility with native modules
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# Stage 2: Build the production application
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# Stage 3: Production container execution runner
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1002 nextjs

# Copy static assets and client-side builds
COPY --from=builder /app/public ./public

# Setup standalone compilation files and directories
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Next.js standalone tracing copies only necessary files into .next/standalone
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# server.js is generated by Next.js standalone builder inside .next/standalone
CMD ["node", "server.js"]
